2022-11-09 15:18:15,362 - root - DEBUG - Connection active
2022-11-09 15:18:15,370 - root - INFO - Recieved CMC_Q02_MAT_PLANT_ATTR.csv
2022-11-09 15:18:15,399 - root - INFO - File CMC_Q02_MAT_PLANT_ATTR.csv stored successfully
2022-11-09 15:18:15,400 - root - INFO -  [*] Waiting for messages.
2022-11-09 15:18:15,484 - root - DEBUG - Connection active
2022-11-09 15:18:15,488 - root - INFO - Recieved CMC_Q02_TCURR.csv
2022-11-09 15:18:15,499 - root - INFO - File CMC_Q02_TCURR.csv stored successfully
2022-11-09 15:18:15,499 - root - INFO -  [*] Waiting for messages.
2022-11-09 15:18:15,587 - root - DEBUG - Connection active
2022-11-09 15:18:15,587 - root - INFO - Recieved dads.txt
2022-11-09 15:18:15,589 - root - INFO - File dads.txt stored successfully
2022-11-09 15:18:15,589 - root - INFO -  [*] Waiting for messages.
2022-11-09 15:18:15,614 - root - DEBUG - Connection active
2022-11-09 15:18:15,615 - root - INFO - Recieved fdsfdsf.txt
2022-11-09 15:18:15,617 - root - INFO - File fdsfdsf.txt stored successfully
2022-11-09 15:18:15,618 - root - INFO -  [*] Waiting for messages.
2022-11-09 15:18:15,646 - root - DEBUG - Connection active
2022-11-09 15:18:15,647 - root - INFO - Recieved mike.txt
2022-11-09 15:18:15,652 - root - INFO - File mike.txt stored successfully
2022-11-09 15:18:15,652 - root - INFO -  [*] Waiting for messages.
2022-11-09 15:18:15,677 - root - DEBUG - Connection active
2022-11-09 15:18:15,678 - root - INFO - Recieved one.txt
2022-11-09 15:18:15,679 - root - INFO - File one.txt stored successfully
2022-11-09 15:18:15,679 - root - INFO -  [*] Waiting for messages.
2022-11-09 15:18:33,286 - root - ERROR - Connection closed by Broker
2022-11-09 15:18:33,297 - root - ERROR - Connection check failed, sleeping 5 seconds
2022-11-09 15:18:38,318 - root - ERROR - Unknown Connection Failure, network might be down..
2022-11-09 15:18:38,319 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\rfranqui\OneDrive - Entegris\Documents\P\Projects\RabbitMQ\recieve.py", line 138, in main
    connection = pika.BlockingConnection(pika.ConnectionParameters(host='localhost'))
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 360, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.IncompatibleProtocolError: StreamLostError: ('Transport indicated EOF',)

2022-11-09 15:18:38,320 - root - INFO - Dev Mode: Initiating Connection to RabbitMQ Instance
2022-11-09 15:18:38,330 - root - ERROR - Dev Mode: Connection to RabbitMQ unsucesfull, retying in 5 seconds
2022-11-09 15:18:43,337 - root - INFO - Dev Mode: Initiating Connection to RabbitMQ Instance
2022-11-09 15:18:47,420 - root - ERROR - Dev Mode: Connection to RabbitMQ unsucesfull, retying in 5 seconds
2022-11-09 15:18:52,434 - root - INFO - Dev Mode: Initiating Connection to RabbitMQ Instance
2022-11-09 15:18:56,516 - root - ERROR - Dev Mode: Connection to RabbitMQ unsucesfull, retying in 5 seconds
2022-11-09 15:19:01,519 - root - INFO - Dev Mode: Initiating Connection to RabbitMQ Instance
2022-11-09 15:19:05,604 - root - ERROR - Dev Mode: Connection to RabbitMQ unsucesfull, retying in 5 seconds
2022-11-09 15:19:10,614 - root - INFO - Dev Mode: Initiating Connection to RabbitMQ Instance
2022-11-09 15:19:14,701 - root - ERROR - Dev Mode: Connection to RabbitMQ unsucesfull, retying in 5 seconds
