2022-11-09 15:17:21,958 - root - ERROR - Connection to RabbitMQ lost, check that RabbitMQ instance is still working
2022-11-09 15:17:21,965 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\rfranqui\OneDrive - Entegris\Documents\P\Projects\RabbitMQ\send.py", line 270, in main
    connection.close()
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 809, in close
    channel.close(reply_code, reply_text)
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 1539, in close
    self._flush_output(lambda: self.is_closed)
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 1353, in _flush_output
    self._connection._flush_output(lambda: self.is_closed, *waiters)
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 523, in _flush_output
    raise self._closed_result.value.error
pika.exceptions.ConnectionClosedByBroker: (320, "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'")

2022-11-09 15:17:21,968 - root - INFO - Will Attempt Reconection in 5 seconds
2022-11-09 15:17:27,013 - root - ERROR - Connection check failed, sleeping 5 seconds
2022-11-09 15:17:32,024 - root - ERROR - Fatal Error
2022-11-09 15:17:32,024 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\rfranqui\OneDrive - Entegris\Documents\P\Projects\RabbitMQ\send.py", line 252, in main
    if checkConnection() == True:
  File "C:\Users\rfranqui\OneDrive - Entegris\Documents\P\Projects\RabbitMQ\send.py", line 126, in checkConnection
    return connect_open
UnboundLocalError: local variable 'connect_open' referenced before assignment

2022-11-09 15:17:32,025 - root - INFO - Will Attempt Reconection in 5 seconds
2022-11-09 15:17:41,121 - root - ERROR - Connection check failed, sleeping 5 seconds
2022-11-09 15:17:46,133 - root - ERROR - Fatal Error
2022-11-09 15:17:46,134 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\rfranqui\OneDrive - Entegris\Documents\P\Projects\RabbitMQ\send.py", line 252, in main
    if checkConnection() == True:
  File "C:\Users\rfranqui\OneDrive - Entegris\Documents\P\Projects\RabbitMQ\send.py", line 126, in checkConnection
    return connect_open
UnboundLocalError: local variable 'connect_open' referenced before assignment

2022-11-09 15:17:46,135 - root - INFO - Will Attempt Reconection in 5 seconds
2022-11-09 15:17:55,249 - root - ERROR - Connection check failed, sleeping 5 seconds
2022-11-09 15:18:00,265 - root - ERROR - Fatal Error
2022-11-09 15:18:00,266 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\rfranqui\OneDrive - Entegris\Documents\P\Projects\RabbitMQ\send.py", line 252, in main
    if checkConnection() == True:
  File "C:\Users\rfranqui\OneDrive - Entegris\Documents\P\Projects\RabbitMQ\send.py", line 126, in checkConnection
    return connect_open
UnboundLocalError: local variable 'connect_open' referenced before assignment

2022-11-09 15:18:00,266 - root - INFO - Will Attempt Reconection in 5 seconds
2022-11-09 15:18:05,286 - root - ERROR - Connection check failed, sleeping 5 seconds
2022-11-09 15:18:10,296 - root - ERROR - Fatal Error
2022-11-09 15:18:10,297 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\rfranqui\OneDrive - Entegris\Documents\P\Projects\RabbitMQ\send.py", line 252, in main
    if checkConnection() == True:
  File "C:\Users\rfranqui\OneDrive - Entegris\Documents\P\Projects\RabbitMQ\send.py", line 126, in checkConnection
    return connect_open
UnboundLocalError: local variable 'connect_open' referenced before assignment

2022-11-09 15:18:10,298 - root - INFO - Will Attempt Reconection in 5 seconds
2022-11-09 15:18:15,322 - root - DEBUG - Connection active
2022-11-09 15:18:15,346 - root - INFO - Moved \CMC_Q02_MAT_PLANT_ATTR.csv' to long term storage
2022-11-09 15:18:15,449 - root - DEBUG - Connection active
2022-11-09 15:18:15,470 - root - INFO - Moved \CMC_Q02_TCURR.csv' to long term storage
2022-11-09 15:18:15,556 - root - DEBUG - Connection active
2022-11-09 15:18:15,572 - root - INFO - Moved \dads.txt' to long term storage
2022-11-09 15:18:15,590 - root - DEBUG - Connection active
2022-11-09 15:18:15,606 - root - INFO - Moved \fdsfdsf.txt' to long term storage
2022-11-09 15:18:15,620 - root - DEBUG - Connection active
2022-11-09 15:18:15,638 - root - INFO - Moved \mike.txt' to long term storage
2022-11-09 15:18:15,654 - root - DEBUG - Connection active
2022-11-09 15:18:15,670 - root - INFO - Moved \one.txt' to long term storage
2022-11-09 15:18:15,675 - root - INFO - No new files will check in 5 seconds
2022-11-09 15:18:20,691 - root - INFO - No new files will check in 5 seconds
